### ISSUE TITLE
Make ansible task syntax consistent

### ISSUE THREAD

**Issue by alanctkc** [alanctkc/dotfiles#81]
Instead of:

```yaml
pacman: name=foo
        state=installed
```

Do:
```yaml
pacman:
  name: foo
  state: installed
```
